### ISSUE TITLE
Update to SDK3

### ISSUE THREAD

**Issue by dirkg173** [mapulu/com.abus#1]
Hi @mapulu,

Are you planning to update the app to SDK3?
I have 7 Abus smoke detectors in use and it would be sad if I can no longer use them with the new Homey Pro (2023).
I have absolutely no idea about programming unfortunately, but if I can support in any other way, please let me know.

Kind regards
Dirk

**Comment by skloepp2** [comment]
Hey Dirk,

a bit late but better late that never :-D
https://github.com/skloepp2/com.abus.homey

Kind regards,
Sascha

**Comment by dirkg173** [comment]
Hey Sascha,

Even though I was able to add the Abus smoke detectors via the Heiman app, it's great to see that the app is being continued. Thank you for that!

Kind regards,
Dirk
